AWSTemplateFormatVersion: "2010-09-09"
Description: Demo VPC 1
Resources:
 MyVPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: "10.77.0.0/16"
    InstanceTenancy: default
    Tags:
       - Key: Name
         Value: Demo VPC 1
       - Key: Environment
         Value: TEST
 MySubnet:
   Type: AWS::EC2::Subnet
   Properties:
     AvailabilityZone: us-east-1a
     CidrBlock: "10.77.2.0/24"
     Tags:
       - Key: Name
         Value: Subnet-1-us-east-1a
     VpcId: !Ref MyVPC
