
AWSTemplateFormatVersion: 2010-09-09
  
Resources:
  NewVolume:
    Type: AWS::EC2::Volume
    Properties: 
      Size: 100
      Encrypted: true
      AvailabilityZone: 'us-east-1a'
      Tags:
        - Key: Name
          Value: My-EBS-Deletion-Policy
