AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyWebEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "Web-EC2-Instance"  
    DependsOn: MyDBEC2Instance

  MyDBEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "DB-EC2-Instance"  
