Resources:
  SSHSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SSH Security Group
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/8"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
      Tags:
        - Key: "Name"
          Value: "SSH Security Group - Drift Test"

  HTTPSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: HTTP Security Group
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/8"
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
      Tags:
        - Key: "Name"
          Value: "HTTP Security Group - Drift Test"

  HTTPSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: HTTPs Security Group
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/8"
          FromPort: 443
          ToPort: 443
          IpProtocol: tcp
      Tags:
        - Key: "Name"
          Value: "HTTPS Security Group - Drift Test"
